// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIW5vZ2W564pWYYsm6wspiY-tIaYI2WvQ',
    appId: '1:874267964463:android:6b9b6c4b4b81d6eff842da',
    messagingSenderId: '874267964463',
    projectId: 'chatapp-40d18',
    storageBucket: 'chatapp-40d18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYCE0Hpga9oxqR0pt_y5msmN-C1ZZorP0',
    appId: '1:874267964463:ios:e535ec6164168f5df842da',
    messagingSenderId: '874267964463',
    projectId: 'chatapp-40d18',
    storageBucket: 'chatapp-40d18.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW2Flz8SIidUYPJbq_PXmYkr-QnRjZrJ0',
    appId: '1:874267964463:web:b07b4201bc676e44f842da',
    messagingSenderId: '874267964463',
    projectId: 'chatapp-40d18',
    authDomain: 'chatapp-40d18.firebaseapp.com',
    storageBucket: 'chatapp-40d18.appspot.com',
    measurementId: 'G-MZ9YWNTVV4',
  );
}
